spring:
  application:
    name: anyosa-payments
  config:
    import: optional:configserver:http://${CONFIG_USER:configuser}:${CONFIG_PASS:configpass}@${CONFIG_HOST:localhost}:8888
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/diegoanyosa_db?currentSchema=payments}
    username: ${DB_USER:dauser}
    password: ${DB_PASS:dapassword}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: payments
  flyway:
    enabled: true
    schemas: payments
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8083

jwt:
  secret: ${JWT_SECRET:change-me-in-production-minimum-32-chars-long!}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
